work_dir:
seed: 3407
device: cuda:0
comment: "debug"

# env:
env:
  id: Hopper-v5
  info:
    state_shape:
    action_shape:
    action_dtype:

# log
log:
  record_param:
    - comment
    - seed
    - agent.algo
    - env.id
  console_output: true

backup_code:
  enable: true
  files:
    - src/
    - conf/
    - requirements.txt

# train
train:
  max_steps: 1000_000
  eval_interval: 5_000

# algo
defaults:
  - agent: ppo
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled
  - _self_
  
hydra:  
  output_subdir: null
  run:
    dir: .