seed: 3407
device: cuda:0
comment: ""

# env:
env:
  id: Hopper-v5
  info:
    state_shape:
    action_shape:
    action_dtype:

# train
train:
  max_steps: 1000_000
  eval_interval: 5_000

# manager
manager:
  root_dir: ./logs
  code:
    enable: true
    src: 
      - ./src
      - ./train_agent.py
  eval_only: false
  tracking:
    project_name: benchmark
    experiment_name: ${env.id}/${agent.algo}
    default_backend: 
      - tensorboard

# algo
defaults:
  - agent: ppo
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled
  - _self_
  
hydra:  
  output_subdir: null
  run:
    dir: .